server:
  port: ${SERVER_PORT:8083}
spring:
  application:
    name: tp3-3
  datasource:
    url: jdbc:postgresql://localhost:5432/tp3-3
    username: head
    password: 456890
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  servlet:
    multipart:
      #      max-file-size: 128MB
      #      max-request-size: 128MB
      enabled: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html